import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

import { useAppDispatch, useAppSelector } from "../redux/hooks";
import { authWithGoogle, selectUser } from "../redux/features/auth/authSlice";
import { useDispatch } from "react-redux";
import { AppDispatch } from "../redux";

const Home: NextPage = () => {
  const dispatch = useDispatch<AppDispatch>();
  const user = useAppSelector(selectUser);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        THe name is `{JSON.stringify(user?.email)}`
        <button
          onClick={() => {
            console.log("touched!");
            //  dispatch(signInGoogle()).payload
            console.log(dispatch(authWithGoogle()));
          }}
        >
          Authenticate!!
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
